# Generated by Django 4.2 on 2023-05-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name of the genre', max_length=50, verbose_name='Genre name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='author',
            field=models.CharField(blank=True, help_text='Enter the author of the artwork', max_length=50, null=True, verbose_name='Artwork author'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='date',
            field=models.DateTimeField(blank=True, help_text='Enter a date of the artwork', null=True, verbose_name='Artwork date'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the artwork', null=True, upload_to='img/', verbose_name='Artwork image'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description of the artwork', null=True, verbose_name='Artwork description'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(help_text='Enter a title of the artwork', max_length=50, verbose_name='Artwork title'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre of the artwork', to='artgallery.genre'),
        ),
    ]
