# Generated by Django 4.2 on 2023-05-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0003_alter_artwork_date_alter_artwork_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='date',
        ),
        migrations.AddField(
            model_name='artwork',
            name='year',
            field=models.IntegerField(blank=True, help_text='Enter a year of the artwork.', null=True, verbose_name='Artwork year'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='author',
            field=models.CharField(blank=True, help_text='Enter an author of the artwork', max_length=50, null=True, verbose_name='Artwork author'),
        ),
    ]
