# Generated by Django 4.2 on 2023-05-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0004_remove_artwork_date_artwork_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name of the author.', max_length=50, verbose_name='Author name')),
                ('born_year', models.IntegerField(blank=True, help_text='Enter a born year of the author.', null=True, verbose_name='Author born year')),
                ('biography', models.TextField(blank=True, help_text='Enter a biography of the author.', null=True, verbose_name='Author biography')),
                ('image', models.ImageField(blank=True, help_text='Upload an image of the author.', null=True, upload_to='img/authors/', verbose_name='Author image')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['-name'],
            },
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['-name'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='author',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the artwork.', null=True, upload_to='img/artworks/', verbose_name='Artwork image'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='author',
            field=models.ManyToManyField(help_text='Select an author of the artwork.', to='artgallery.author'),
        ),
    ]
