# Generated by Django 4.2 on 2023-06-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0005_author_alter_genre_options_remove_artwork_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
